// Command genspellenums parses the Turtle/mangos server-source spell enums
// (SpellDefines.h, SpellAuraDefines.h) into backend/database/helpers/spell_enums.go.
//
// The spell effect/aura *type* names and attribute-flag labels don't exist in
// any client file (the client engine acts on the numeric ids but never names
// them), so they come from the authoritative server source instead. Re-run when
// the server source changes.
//
// Usage:
//
//	go run ./cmd/genspellenums "<path to src/game/Spells>" [out.go]
package main

import (
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"sort"
	"strconv"
	"strings"
)

var enumLineRe = regexp.MustCompile(`^\s*([A-Z][A-Z0-9_]+)\s*=\s*(0x[0-9A-Fa-f]+|\d+)`)

// parseEnum returns id->CONSTANT_NAME for the named `enum X { ... };` block.
func parseEnum(src, name string) map[int64]string {
	out := map[int64]string{}
	i := strings.Index(src, "enum "+name)
	if i < 0 {
		return out
	}
	body := src[i:]
	if b := strings.Index(body, "{"); b >= 0 {
		body = body[b+1:]
	}
	if e := strings.Index(body, "};"); e >= 0 {
		body = body[:e]
	}
	for _, line := range strings.Split(body, "\n") {
		m := enumLineRe.FindStringSubmatch(line)
		if m == nil {
			continue
		}
		var v int64
		if strings.HasPrefix(m[2], "0x") {
			v, _ = strconv.ParseInt(m[2][2:], 16, 64)
		} else {
			v, _ = strconv.ParseInt(m[2], 10, 64)
		}
		out[v] = m[1]
	}
	return out
}

// friendly turns SPELL_AURA_PERIODIC_DAMAGE (after stripping a prefix) into
// "Periodic Damage".
func friendly(name string, prefixes []string) string {
	for _, p := range prefixes {
		if strings.HasPrefix(name, p) {
			name = name[len(p):]
			break
		}
	}
	words := strings.Split(strings.ToLower(name), "_")
	for i, w := range words {
		if w == "" {
			continue
		}
		words[i] = strings.ToUpper(w[:1]) + w[1:]
	}
	return strings.Join(words, " ")
}

func main() {
	if len(os.Args) < 2 {
		fmt.Fprintln(os.Stderr, `usage: genspellenums "<src/game/Spells>" [out.go]`)
		os.Exit(2)
	}
	dir := os.Args[1]
	out := "backend/database/helpers/spell_enums.go"
	if len(os.Args) > 2 {
		out = os.Args[2]
	}

	defines, err := os.ReadFile(filepath.Join(dir, "SpellDefines.h"))
	if err != nil {
		fatal("read SpellDefines.h", err)
	}
	auras, err := os.ReadFile(filepath.Join(dir, "SpellAuraDefines.h"))
	if err != nil {
		fatal("read SpellAuraDefines.h", err)
	}

	effects := parseEnum(string(defines), "SpellEffects")
	auraTypes := parseEnum(string(auras), "AuraType")

	// Attribute flags: each enum maps to one spell_template column (field index).
	attrEnums := []struct {
		name  string
		field int
	}{
		{"SpellAttributes", 0},
		{"SpellAttributesEx", 1},
		{"SpellAttributesEx2", 2},
		{"SpellAttributesEx3", 3},
		{"SpellAttributesEx4", 4},
		{"SpellAttributesCustom", 5},
	}
	attrPrefixes := []string{
		"SPELL_ATTR_EX4_", "SPELL_ATTR_EX3_", "SPELL_ATTR_EX2_", "SPELL_ATTR_EX_",
		"SPELL_ATTR_CUSTOM_", "SPELL_ATTR_",
	}

	var b strings.Builder
	b.WriteString("// Code generated by cmd/genspellenums from the Turtle server source. DO NOT EDIT.\n")
	b.WriteString("// Spell effect/aura type names and attribute-flag labels aren't in any client\n")
	b.WriteString("// file; they come from the server enums (SpellDefines.h / SpellAuraDefines.h).\n\n")
	b.WriteString("package helpers\n\n")

	writeIntMap(&b, "SpellEffectNames", effects, []string{"SPELL_EFFECT_"})
	writeIntMap(&b, "AuraTypeNames", auraTypes, []string{"SPELL_AURA_"})

	b.WriteString("// SpellAttrFlag is one attribute bit: Field selects the spell_template column\n")
	b.WriteString("// (0=attributes, 1=attributesEx .. 4=attributesEx4, 5=customFlags).\n")
	b.WriteString("type SpellAttrFlag struct {\n\tField int\n\tMask  uint32\n\tName  string\n}\n\n")
	b.WriteString("var SpellAttrFlags = []SpellAttrFlag{\n")
	for _, e := range attrEnums {
		flags := parseEnum(string(defines), e.name)
		var keys []int64
		for k := range flags {
			keys = append(keys, k)
		}
		sort.Slice(keys, func(i, j int) bool { return keys[i] < keys[j] })
		for _, k := range keys {
			b.WriteString(fmt.Sprintf("\t{Field: %d, Mask: 0x%08X, Name: %q},\n", e.field, uint32(k), friendly(flags[k], attrPrefixes)))
		}
	}
	b.WriteString("}\n")

	if err := os.WriteFile(out, []byte(b.String()), 0644); err != nil {
		fatal("write output", err)
	}
	fmt.Printf("✓ wrote %s: %d effects, %d auras, %d attr flags\n", out, len(effects), len(auraTypes), countFlags(string(defines), attrEnums))
}

func writeIntMap(b *strings.Builder, varName string, m map[int64]string, prefixes []string) {
	var keys []int64
	for k := range m {
		keys = append(keys, k)
	}
	sort.Slice(keys, func(i, j int) bool { return keys[i] < keys[j] })
	fmt.Fprintf(b, "var %s = map[int]string{\n", varName)
	for _, k := range keys {
		fmt.Fprintf(b, "\t%d: %q,\n", k, friendly(m[k], prefixes))
	}
	b.WriteString("}\n\n")
}

func countFlags(src string, enums []struct {
	name  string
	field int
}) int {
	n := 0
	for _, e := range enums {
		n += len(parseEnum(src, e.name))
	}
	return n
}

func fatal(ctx string, err error) {
	fmt.Fprintf(os.Stderr, "error (%s): %v\n", ctx, err)
	os.Exit(1)
}
