// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';
import {main} from '../models';
import {services} from '../models';

export function AddFavorite(arg1:number,arg2:string):Promise<models.FavoriteResult>;

export function AdvancedSearch(arg1:models.SearchFilter):Promise<models.SearchResult>;

export function BrowseCreaturesByFamilyPaged(arg1:number,arg2:string,arg3:number,arg4:number):Promise<main.CreaturePageResult>;

export function BrowseCreaturesByType(arg1:number,arg2:string):Promise<Array<models.Creature>>;

export function BrowseCreaturesByTypePaged(arg1:number,arg2:string,arg3:number,arg4:number):Promise<main.CreaturePageResult>;

export function BrowseItems(arg1:models.SearchFilter):Promise<models.SearchResult>;

export function BrowseItemsByClass(arg1:number,arg2:number,arg3:string):Promise<Array<models.Item>>;

export function BrowseItemsByClassAndSlot(arg1:number,arg2:number,arg3:number,arg4:string):Promise<Array<models.Item>>;

export function CheckForUpdate():Promise<main.UpdateInfo>;

export function CheckNewItems(arg1:number,arg2:number):Promise<Array<services.RemoteItem>>;

export function CheckNewQuests(arg1:number,arg2:number):Promise<Array<services.RemoteQuest>>;

export function FixMissingIcons(arg1:string,arg2:number):Promise<main.FixMissingIconsResult>;

export function FixSingleItemIcon(arg1:number):Promise<main.FixMissingIconsResult>;

export function FullSyncItems(arg1:number,arg2:boolean,arg3:number):Promise<string>;

export function FullSyncNpcs(arg1:number,arg2:number):Promise<string>;

export function FullSyncObjects(arg1:number,arg2:number):Promise<string>;

export function FullSyncQuests(arg1:number,arg2:number):Promise<string>;

export function GetAllFavorites():Promise<Array<models.FavoriteItem>>;

export function GetBeastFamilies():Promise<Array<models.BeastFamily>>;

export function GetCategories():Promise<Array<string>>;

export function GetCategoryItems(arg1:number):Promise<Array<models.Item>>;

export function GetChildCategories(arg1:number):Promise<Array<models.Category>>;

export function GetCreatureDetail(arg1:number):Promise<models.CreatureDetail>;

export function GetCreatureLoot(arg1:number):Promise<Array<models.LootItem>>;

export function GetCreatureTypes():Promise<Array<models.CreatureType>>;

export function GetDataStatus():Promise<main.DataStatus>;

export function GetFactionDetail(arg1:number):Promise<models.FactionDetail>;

export function GetFactions():Promise<Array<models.Faction>>;

export function GetFavoriteCategories():Promise<Array<models.FavoriteCategory>>;

export function GetFavoritesByCategory(arg1:string):Promise<Array<models.FavoriteItem>>;

export function GetFlightContinents():Promise<Array<main.FlightContinent>>;

export function GetFlightData(arg1:number):Promise<main.FlightData>;

export function GetIconUsage(arg1:string):Promise<main.IconUsage>;

export function GetInstances(arg1:string):Promise<Array<string>>;

export function GetItemClasses():Promise<Array<models.ItemClass>>;

export function GetItemDetail(arg1:number):Promise<models.ItemDetail>;

export function GetItemRandomSuffixes(arg1:number):Promise<Array<main.ItemRandomSuffix>>;

export function GetItemSetDetail(arg1:number):Promise<models.ItemSetDetail>;

export function GetItemSets():Promise<Array<models.ItemSetBrowse>>;

export function GetItemStatTypes():Promise<Array<models.StatType>>;

export function GetLocalImage(arg1:string,arg2:string):Promise<main.ImageResult>;

export function GetLoot(arg1:string,arg2:string,arg3:string):Promise<main.LegacyBossLoot>;

export function GetMissingAtlasLootItems(arg1:number):Promise<Array<services.MissingItem>>;

export function GetNpcDetails(arg1:number):Promise<services.NpcFullDetails>;

export function GetObjectDetail(arg1:number):Promise<models.GameObjectDetail>;

export function GetObjectTypes():Promise<Array<models.ObjectType>>;

export function GetObjectsByType(arg1:number,arg2:string):Promise<Array<models.GameObject>>;

export function GetQuestCategories():Promise<Array<models.QuestCategory>>;

export function GetQuestCategoriesByGroup(arg1:number):Promise<Array<models.QuestCategoryEnhanced>>;

export function GetQuestCategoryGroups():Promise<Array<models.QuestCategoryGroup>>;

export function GetQuestDetail(arg1:number):Promise<models.QuestDetail>;

export function GetQuestsByCategory(arg1:number):Promise<Array<models.Quest>>;

export function GetQuestsByEnhancedCategory(arg1:number,arg2:string):Promise<Array<models.Quest>>;

export function GetRaces():Promise<Array<models.Race>>;

export function GetRootCategories():Promise<Array<models.Category>>;

export function GetSpellClasses():Promise<Array<models.SpellClass>>;

export function GetSpellDetail(arg1:number):Promise<models.SpellDetail>;

export function GetSpellSkillCategories():Promise<Array<models.SpellSkillCategory>>;

export function GetSpellSkillsByCategory(arg1:number):Promise<Array<models.SpellSkill>>;

export function GetSpellSkillsByClass(arg1:number):Promise<Array<models.SpellSkill>>;

export function GetSpellsBySkill(arg1:number,arg2:string):Promise<Array<models.Spell>>;

export function GetSyncStats():Promise<Record<string, any>>;

export function GetTables(arg1:string,arg2:string):Promise<Array<models.AtlasTable>>;

export function GetTalentClasses():Promise<Array<main.TalentClassInfo>>;

export function GetTalentTrees(arg1:string):Promise<main.TalentClassData>;

export function GetTooltipData(arg1:number):Promise<models.TooltipData>;

export function GetWorldData():Promise<main.WorldData>;

export function GetZoneData(arg1:number,arg2:string):Promise<main.ZoneData>;

export function GetZoneDetail(arg1:number):Promise<models.ZoneDetail>;

export function GetZoneLoot(arg1:number):Promise<Array<models.ZoneLoot>>;

export function GetZoneNames():Promise<Array<models.ZoneNameInfo>>;

export function GetZones():Promise<Array<models.ZoneListEntry>>;

export function IsFavorite(arg1:number):Promise<boolean>;

export function ListLocalIcons():Promise<Array<main.IconEntry>>;

export function MatchFlightmasters():Promise<void>;

export function RebuildSpawnZones(arg1:string):Promise<main.ImportReport>;

export function RefreshNpcImages(arg1:number):Promise<services.NpcFullDetails>;

export function RemoveFavorite(arg1:number):Promise<models.FavoriteResult>;

export function RenderNpcModel(arg1:number,arg2:number,arg3:string):Promise<boolean>;

export function RunCacheImport(arg1:string):Promise<main.ImportReport>;

export function RunClientImport(arg1:string):Promise<main.ImportReport>;

export function SearchCreatures(arg1:string):Promise<Array<models.Creature>>;

export function SearchItems(arg1:string):Promise<Array<models.Item>>;

export function SearchObjects(arg1:string):Promise<Array<models.GameObject>>;

export function SearchQuests(arg1:string):Promise<Array<models.Quest>>;

export function SearchSpells(arg1:string):Promise<Array<models.Spell>>;

export function SelectClientFolder(arg1:string):Promise<string>;

export function StopSync():Promise<string>;

export function SyncMissingAtlasLoot(arg1:number,arg2:number):Promise<services.ImportResult>;

export function SyncNpcData(arg1:number):Promise<services.NpcFullDetails>;

export function SyncObject(arg1:number):Promise<models.GameObjectDetail>;

export function SyncQuestData(arg1:number):Promise<models.QuestDetail>;

export function SyncSingleItem(arg1:number):Promise<services.SyncItemResult>;

export function SyncSingleSpell(arg1:number):Promise<services.SyncSpellResult>;

export function ToggleFavorite(arg1:number,arg2:string):Promise<models.FavoriteResult>;

export function UpdateFavoriteCategory(arg1:number,arg2:string):Promise<models.FavoriteResult>;

export function UpdateFavoriteStatus(arg1:number,arg2:number):Promise<models.FavoriteResult>;

export function WaitForReady():Promise<boolean>;

export function WhatsNew():Promise<main.WhatsNewReport>;
