// Export all database tab components
export { default as ItemsTab } from './ItemsTab'
export { default as SetsTab } from './SetsTab'
export { default as NPCsTab } from './NPCsTab'
export { default as QuestsTab } from './QuestsTab'
export { default as ObjectsTab } from './ObjectsTab'
export { default as ZonesTab } from './ZonesTab'
export { default as SpellsTab } from './SpellsTab'
export { default as FactionsTab } from './FactionsTab'
export { default as RacesTab } from './RacesTab'
export { default as IconsTab } from './IconsTab'
